### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by gaurav-gogia** [gaurav-gogia/KameKazi#12]
Add a small landing page for this little application.
Going with the theme please make a small landing page.

Existing first/index page could have this overlay screen that comes when the user opens the site. Then either on button click or after some time, remove that welcome page/screen and show main content.

**Comment by faaizalikhan1** [comment]
Hi, I'd like to work on this!

**Comment by gaurav-gogia** [comment]
Sure ^.^

**Comment by faaizalikhan1** [comment]
@DesmondANIMUS Thanks! I'll get back to you tomorrow with the code!

**Comment by gaurav-gogia** [comment]
Awesome work @goprime10
