### ISSUE TITLE
Make secret.html page AMP compliant

### ISSUE THREAD

**Issue by gaurav-gogia** [gaurav-gogia/KameKazi#18]

**Comment by nsrivastava645** [comment]
I'm good at HTML can you just let me know whether a simple hTML page would do in this issue?

**Comment by gaurav-gogia** [comment]
Yea, sure, just make it AMP compliant and make it look good. A modern and cute design :)

The current one is cool too so, you can either keep it or update it. I'm cool as long as it's AMP compliant :)
