### ISSUE TITLE
Loading banner view

### ISSUE THREAD

**Issue by rorschach217** [gaurav-gogia/KameKazi#50]
we can add a button named next or go instead of 3-5 second waiting of the banner to slide up. 
of first watch it is like the page is of only loading banner. for 5 second i was confused what to do.
you can do lower the timer of slide up effect or out a counter in decreasing order so user will wait. for it.

**Comment by gaurav-gogia** [comment]
I see. Sounds good. Do you want to take this issue @rorschach217 ?? :)
