### ISSUE TITLE
make it look good

### ISSUE THREAD

**Issue by gaurav-gogia** [gaurav-gogia/KameKazi#6]
The homepage has no design at all. Make it look pretty. Please don't use any libraries or frameworks. 

Ideal approach:
Pure CSS. Feel free to ask for resources or any other related help. Will try and help you solve this issue, it'll be fun.

Feel free to use embedded CSS in html pages.

**Bonus:**
Implement AMP.

**Comment by jmhobbs** [comment]
Are you ok with a very simple look?  Big fonts, flat design?

**Comment by gaurav-gogia** [comment]
Yep, aiming for a calm & minimalistic design here :)

**Comment by tarunjindal790** [comment]
Hey,I tried to make some basic changes here #8 . Thank you :)

**Comment by gaurav-gogia** [comment]
> Hey,I tried to make some basic changes here #8 . Thank you :)

Appreciate the effort but I kinda had to go for the other PR. I hope you understand.
